export const eventActionType={
    ADD_EVENT:"ADD_EVENT",
    DELETE_EVENT:"DELETE_EVENT",
    UPDATE_EVENT:"UPDATE_EVENT",
    VIEW_EVENT:"VIEW_EVENT",
    GET_ALL_EVENT:"GET_ALL_EVENT",
    SET_EVETS_AXIOS:"SET_EVETS_AXIOS"
}