export const localBusinessesActionType ={
    ADD_LBPRODUCT:"ADD_LBPRODUCT",
    DELETE_LBPRODUCT:"DELETE_LBPRODUCT",
    UPDATE_LBPRODUCT:"UPDATE_LBPRODUCT",
    VIEW_LBPRODUCT:"VIEW_LBPRODUCT",
    GET_ALL_LBPRODUCT:"GET_ALL_LBPRODUCT",
    SET_LBPRODUCTS_AXIOS:"SET_LBPRODUCTS_AXIOS"
}