export const recipeActionType = {
  ADD_RECIPE: "ADD_RECIPE",
  DELETE_RECIPE: "DELETE_RECIPE",
  UPDATE_RECIPE: "UPDATE_RECIPE",
  VIEW_RECIPE: "VIEW_RECIPE",
  GET_ALL_RECIPE: "GET_ALL_RECIPE",
  SET_RECIPE_AXIOS: "SET_RECIPE_AXIOS",
};
