const HandCraftsItems = [
    {
      key: 1,
      image: "https://media.timeout.com/images/101852779/1024/576/image.jpg",
      title: "Wood Pots",
      discription:"Sri Lankan wood pots, also known as hatta in Sinhala language, are handcrafted pots made from a variety of woods, including teak, mahogany, and ebony. These pots are traditionally used for cooking, serving, and storing food, and are a common sight in Sri Lankan households and restaurants. The pots are made using a traditional process that involves carving and shaping the wood into the desired shape and size, and then polishing and finishing it with natural oils to enhance the wood's durability and shine. The unique characteristics of each type of wood used to make the pots give them distinct qualities, such as heat resistance, natural beauty, and durability. Sri Lankan wood pots are not only functional but also decorative, with intricate designs and patterns carved into the surface of the pots, making them popular as souvenirs and gifts for visitors to the country.",
      discriptionLong:"Sri Lankan wood pots, also known as hatta in Sinhala language, are handcrafted pots made from a variety of woods, including teak, mahogany, and ebony. These pots are traditionally used for cooking, serving, and storing food, and are a common sight in Sri Lankan households and restaurants. The pots are made using a traditional process that involves carving and shaping the wood into the desired shape and size, and then polishing and finishing it with natural oils to enhance the wood's durability and shine. The unique characteristics of each type of wood used to make the pots give them distinct qualities, such as heat resistance, natural beauty, and durability. Sri Lankan wood pots are not only functional but also decorative, with intricate designs and patterns carved into the surface of the pots, making them popular as souvenirs and gifts for visitors to the country.",
      place1:"Ambackcka Shop",
      place1Address:"66/2, Ambackcka Shop, Ambakka",
      place1Contact:"Ambackcka Shop",
      place2:"Ambackcka Shop",
      place2Address:"66/2, Ambackcka Shop, Ambakka",
      place2Contact:"Ambackcka Shop",
      place3:"Ambackcka Shop",
      place3Address:"66/2, Ambackcka Shop, Ambakka",
      place3Contact:"Ambackcka Shop",
      place4:"Ambackcka Shop",
      place4Address:"66/2, Ambackcka Shop, Ambakka",
      place4Contact:"Ambackcka Shop",
      place5:"Ambackcka Shop",
      place5Address:"66/2, Ambackcka Shop, Ambakka",
      place5Contact:"Ambackcka Shop"
    //   path: "/",
    //   Selected: true,
    },
    {
      key: 2,
      image: "https://media.timeout.com/images/101852727/380/285/image.jpg",
      title: "Handloom",
      discription:"Long ago handloom was reserved exclusively for the royalty and the renowned in the country and special villages were designated to practice the craft. However, now Handloom is generally found around the island as a self-employed or entrepreneurial activity where this skill which has been passed down from generation to generation has been revived and practised.",
      discriptionLong:"Long ago handloom was reserved exclusively for the royalty and the renowned in the country and special villages were designated to practice the craft. However, now Handloom is generally found around the island as a self-employed or entrepreneurial activity where this skill which has been passed down from generation to generation has been revived and practised.",
      place1:"Ambackcka Shop",
      place1Address:"66/2, Ambackcka Shop, Ambakka",
      place1Contact:"Ambackcka Shop",
      place2:"Ambackcka Shop",
      place2Address:"66/2, Ambackcka Shop, Ambakka",
      place2Contact:"Ambackcka Shop",
      place3:"Ambackcka Shop",
      place3Address:"66/2, Ambackcka Shop, Ambakka",
      place3Contact:"Ambackcka Shop",
      place4:"Ambackcka Shop",
      place4Address:"66/2, Ambackcka Shop, Ambakka",
      place4Contact:"Ambackcka Shop",
      place5:"Ambackcka Shop",
      place5Address:"66/2, Ambackcka Shop, Ambakka",
      place5Contact:"Ambackcka Shop"
    //   path: "/",
    //   Selected: false,
    },
  
    {
      key: 3,
      image: "https://media.timeout.com/images/101852267/380/285/image.jpg",
      title: "Masks",
      discription:"Masks are deeply connected to Sri Lankan folk-lore and take on a functional role where they are used in healing rites and rituals. Known popularly as devil dances, some are dance-drama performances that tell an elaborate story and is enacted by experienced dancers and actors wearing these masks..",
      discriptionLong:"Masks are deeply connected to Sri Lankan folk-lore and take on a functional role where they are used in healing rites and rituals. Known popularly as devil dances, some are dance-drama performances that tell an elaborate story and is enacted by experienced dancers and actors wearing these masks..",
      place1:"Ambackcka Shop",
      place1Address:"66/2, Ambackcka Shop, Ambakka",
      place1Contact:"Ambackcka Shop",
      place2:"Ambackcka Shop",
      place2Address:"66/2, Ambackcka Shop, Ambakka",
      place2Contact:"Ambackcka Shop",
      place3:"Ambackcka Shop",
      place3Address:"66/2, Ambackcka Shop, Ambakka",
      place3Contact:"Ambackcka Shop",
      place4:"Ambackcka Shop",
      place4Address:"66/2, Ambackcka Shop, Ambakka",
      place4Contact:"Ambackcka Shop",
      place5:"Ambackcka Shop",
      place5Address:"66/2, Ambackcka Shop, Ambakka",
      place5Contact:"Ambackcka Shop"
      


    //   path: "/",
    //   Selected: true,
    },
  
    {
      key: 4,
      image: "https://media.timeout.com/images/101852727/380/285/image.jpg",
      title: "Dumbara Weaves",
      discription:"Dumbara weaves, a unique work of art once found only as decorative pieces and mats are now seen integrated into the modern world; it can now be seen infused with designs of wall hangings and decorative items, bags and purses, rugs and carpets along with household utilities such as table mats and sheets..",
      discriptionLong:"Dumbara weaves, a unique work of art once found only as decorative pieces and mats are now seen integrated into the modern world; it can now be seen infused with designs of wall hangings and decorative items, bags and purses, rugs and carpets along with household utilities such as table mats and sheets..",
      place1:"Ambackcka Shop",
      place1Address:"66/2, Ambackcka Shop, Ambakka",
      place1Contact:"Ambackcka Shop",
      place2:"Ambackcka Shop",
      place2Address:"66/2, Ambackcka Shop, Ambakka",
      place2Contact:"Ambackcka Shop",
      place3:"Ambackcka Shop",
      place3Address:"66/2, Ambackcka Shop, Ambakka",
      place3Contact:"Ambackcka Shop",
      place4:"Ambackcka Shop",
      place4Address:"66/2, Ambackcka Shop, Ambakka",
      place4Contact:"Ambackcka Shop",
      place5:"Ambackcka Shop",
      place5Address:"66/2, Ambackcka Shop, Ambakka",
      place5Contact:"Ambackcka Shop"
    //   path: "/",
    //   Selected: true,
    },
    {
      key: 5,
      image: "https://media.timeout.com/images/101852727/380/285/image.jpg",
      title: "Wood Pots",
      discription:"Sri Lankan wood pots, also known as hatta in Sinhala language, are handcrafted pots made from a variety of woods, including teak, mahogany, and ebony. These pots are traditionally used for cooking, serving, and storing food, and are a common sight in Sri Lankan households and restaurants. The pots are made using a traditional process that involves carving and shaping the wood into the desired shape and size, and then polishing and finishing it with natural oils to enhance the wood's durability and shine. The unique characteristics of each type of wood used to make the pots give them distinct qualities, such as heat resistance, natural beauty, and durability. Sri Lankan wood pots are not only functional but also decorative, with intricate designs and patterns carved into the surface of the pots, making them popular as souvenirs and gifts for visitors to the country.",
      discriptionLong:"Sri Lankan wood pots, also known as hatta in Sinhala language, are handcrafted pots made from a variety of woods, including teak, mahogany, and ebony. These pots are traditionally used for cooking, serving, and storing food, and are a common sight in Sri Lankan households and restaurants. The pots are made using a traditional process that involves carving and shaping the wood into the desired shape and size, and then polishing and finishing it with natural oils to enhance the wood's durability and shine. The unique characteristics of each type of wood used to make the pots give them distinct qualities, such as heat resistance, natural beauty, and durability. Sri Lankan wood pots are not only functional but also decorative, with intricate designs and patterns carved into the surface of the pots, making them popular as souvenirs and gifts for visitors to the country.",
      place1:"Ambackcka Shop",
      place1Address:"66/2, Ambackcka Shop, Ambakka",
      place1Contact:"Ambackcka Shop",
      place2:"Ambackcka Shop",
      place2Address:"66/2, Ambackcka Shop, Ambakka",
      place2Contact:"Ambackcka Shop",
      place3:"Ambackcka Shop",
      place3Address:"66/2, Ambackcka Shop, Ambakka",
      place3Contact:"Ambackcka Shop",
      place4:"Ambackcka Shop",
      place4Address:"66/2, Ambackcka Shop, Ambakka",
      place4Contact:"Ambackcka Shop",
      place5:"Ambackcka Shop",
      place5Address:"66/2, Ambackcka Shop, Ambakka",
      place5Contact:"Ambackcka Shop"
    //   path: "/",
    //   Selected: true,
    },
    
  ];
  
  